
micronaut:
  application:
    name: openapi-micronaut
  server:
    port: 8080
    context-path: "/download/7/1/d/71d86715-5596-4529-9b13-da13a5de5b63/"
  security:
    # authentication: bearer | cookie | session | idtoken

jackson:
  serialization:
    writeEnumsUsingToString: true
    writeDatesAsTimestamps: false
  deserialization:
    readEnumsUsingToString: true
    failOnUnknownProperties: false
    failOnInvalidSubtype: false
